// Generated by CoffeeScript 2.1.1
(function() {
  var Config, init;

  Config = class Config {
    constructor() {
      this.module_path = __dirname.split('/');
    }

    settings(type) {
      switch (type) {
        case 'grid':
          return {
            'screen_width': 1200,
            'left_margin': 50,
            'right_margin': 50,
            'top_margin': 50,
            'bottom_margin': 50,
            'header_height': 100,
            'vertical_space_between_items': 100,
            'horisontal_space_between_items': 70,
            'max_num_columns': 8,
            'max_num_columns_in_row': function(row) {
              if (row === 0) {
                return 7;
              } else {
                return 8;
              }
            }
          };
        case 'item':
          return {
            'width': 175,
            'height': 100,
            'border_width': 2
          };
      }
    }

  };

  init = function() {
    return new Config;
  };

  exports.init = init;

}).call(this);
