// Generated by CoffeeScript 2.1.1
(function() {
  var DataParser, init;

  DataParser = class DataParser {
    constructor(json_data) {
      this.data = JSON.parse(json_data)['data'];
    }

    properties_settings() {
      var categories_styles, category, item_type, properties, ref, ref1, ref2, style, style_uid, styles;
      categories_styles = {};
      ref = this.data['categories'];
      for (item_type in ref) {
        category = ref[item_type];
        categories_styles[item_type] = category['style'];
      }
      properties = {};
      ref1 = this.data['categories'];
      for (item_type in ref1) {
        category = ref1[item_type];
        properties[item_type] = category['properties'];
      }
      styles = {};
      ref2 = this.data['styles'];
      for (style_uid in ref2) {
        style = ref2[style_uid];
        styles[style_uid] = style;
      }
      return {
        categories_styles: categories_styles,
        properties: properties,
        styles: styles
      };
    }

  };

  init = function(json_data) {
    return new DataParser(json_data);
  };

  exports.init = init;

}).call(this);
