// Generated by CoffeeScript 2.1.1
(function() {
  var Helpers, init;

  Helpers = class Helpers {
    constructor() {}

    getMaxOfArray(array) {
      return Math.max.apply(null, array);
    }

  };

  init = function() {
    return new Helpers;
  };

  exports.init = init;

}).call(this);
