// Generated by CoffeeScript 1.12.7
(function() {
  var Helpers, init;

  Helpers = (function() {
    function Helpers() {}

    Helpers.prototype.getMaxOfArray = function(array) {
      return Math.max.apply(null, array);
    };

    return Helpers;

  })();

  init = function() {
    return new Helpers;
  };

  exports.init = init;

}).call(this);
