// Generated by CoffeeScript 2.1.1
(function() {
  var Item, init;

  Item = class Item {
    constructor(row, column, drawing_area_center_position) {
      var config;
      config = require("./config").init();
      this.row = row;
      this.column = column;
      this.drawing_area_center_position = drawing_area_center_position;
      this.grid_settings = config.settings('grid');
      this.item_settings = config.settings('item');
    }

    position() {
      return {
        'left': this.left_border_position(),
        'right': this.right_border_position(),
        'top': this.top_border_position(),
        'bottom': this.bottom_border_position()
      };
    }

    left_border_position() {
      var item_width_with_right_space, shift, start_x_position;
      item_width_with_right_space = this.item_settings['width'] + 2 * this.item_settings['border_width'] + this.grid_settings['horisontal_space_between_items'];
      start_x_position = this.drawing_area_center_position - (parseInt(this.item_settings['width']) / 2) - this.item_settings['border_width'];
      shift = (parseInt(this.column) % 2 === 0 ? -1 : 1) * Math.round((parseInt(this.column)) / 2) * item_width_with_right_space;
      return Math.round(start_x_position + shift);
    }

    right_border_position() {
      return Math.round(this.left_border_position() + this.item_settings['width'] + 2 * this.item_settings['border_width']);
    }

    top_border_position() {
      var item_height_with_bottom_space;
      item_height_with_bottom_space = this.item_settings['height'] + 2 * this.item_settings['border_width'] + this.grid_settings['vertical_space_between_items'];
      return Math.round(this.grid_settings['top_margin'] + this.row * item_height_with_bottom_space);
    }

    bottom_border_position() {
      return Math.round(this.top_border_position() + this.item_settings['height'] + 2 * this.item_settings['border_width']);
    }

  };

  init = function(drawing_area_center_position) {
    return function(row, column) {
      return new Item(row, column, drawing_area_center_position);
    };
  };

  exports.init = init;

}).call(this);
