// Generated by CoffeeScript 2.1.1
(function() {
  var Trees, init;

  Trees = class Trees {
    constructor(json_data) {
      this.data_parser = require("./data_parser").init(json_data);
      this.grid = require("./grid").init(this.data_parser.data);
      this.data_matrix = this.grid.matrix();
      this.draw = require("./draw").init(this.grid.width, this.grid.height, this.data_parser.properties_settings());
    }

    svg() {
      return this.draw.items(this.data_matrix).svg();
    }

  };

  init = function(json_data) {
    return new Trees(json_data);
  };

  exports.init = init;

}).call(this);
